export const LOAD_BOOKS = 'LOAD_BOOKS';
export const SET_QUERY = 'SET_QUERY';
export const SET_QUERYTYPE = 'SET_QUERYTYPE';
export const SET_STARTINDEX = 'SET_STARTINDEX';
export const CLEAR_BOOKS = 'CLEAR_BOOKS';
//NEW!
export const LOAD_BOOKS_DESCRIPTION_AUTHOR = 'LOAD_BOOKS_DESCRIPTION_AUTHOR';
export const LOAD_BOOKS_DESCRIPTION_SUBJECT = 'LOAD_BOOKS_DESCRIPTION_SUBJECT';